### ISSUE TITLE
Ansi Color support

### ISSUE THREAD

**Issue by foobit** [benpollarduk/BP.AdventureFramework#51]
Instead of `RenderColor` enum, create a custom type that can support foreground and background colors.
See [Ansi Colors](https://talyian.github.io/ansicolors/) for color examples. Colors can be embedded directly into strings.

```c#
Console.WriteLine("\x1b[38;5;10mWelcome to Game\x1b[0m v0.1");
```
🤔 Having a string extension to convert human readable markup to ansi codes. Could be a good feature.
```c#
Console.WriteLine("[style:header]Welcome to Game[style:default] v0.1".Markup());
```

**Comment by benpollarduk** [comment]
This is a good idea. The GridTextFrame class references System.Console a lot which makes unit testing it hard, so it's probably worth refactoring GridTextFrame so that is uses ANSI for colour setting and other control etc at the same time, then the GridTextFrame is decoupled from the System.Console entirely.
