### ISSUE TITLE
Item Shop

### ISSUE THREAD

**Issue by furesoft** [benpollarduk/BP.AdventureFramework#62]
Add the ability to buy items from a shop or NPC

**Comment by benpollarduk** [comment]
I'm not planning on adding this because this can be implemented currently through conversations or custom commands on items or NPCs. However it is difficult to add well because there's currently no item format that supports owning multiples of an item so currency is difficult to do well, but that's something I've been thinking of for a while and I've added an [issue](https://github.com/benpollarduk/BP.AdventureFramework/issues/68) and will implement next. I'll add instructions how a shop can then be implemented as a document in documentation 👍
